---
global:
  scrape_interval: 30s
  evaluation_interval: 15s
  external_labels:
    monitor: 'homelab'

rule_files:
  - /etc/prometheus/prometheus-alertrules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'docker'
    static_configs:
      - targets: ['loclahost:9323']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['blackbox_expoter:9115']
  - job_name: blackbox_exporter_web
    file_sd_configs:
    - files:
      - /etc/prometheus/blackbox-exporter-file-sd.json
    relabel_configs:
    - source_labels:
      - __address__
      separator: ':'
      regex: '(.+?):(.*)'
      replacement: '$1'
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: blackbox-exporter:9115
      target_label: __address__
